tags:
  - 
    id : 1
    translation: [0, 0, 0]
    rotation: [0, 0, 0, 1]
  - 
    id : 2
    translation: [1.2, 0, 0]
    rotation: [0, 0, 0, 1]
  - 
    id : 3
    translation: [0, 0, -1.2]
    rotation: [0, 0, 0, 1]
  - 
    id : 4
    translation: [1.2, 0, -1.2]
    rotation: [0, 0, 0, 1]
  - 
    id : 5
    translation: [0.6, 0, -2.4]
    rotation: [0, 0, 0, 1]
  - 
    id : 6
    translation: [1.2, 0, -3]
    rotation: [0, 0, 0, 1]
  - 
    id : 8
    translation: [0, 0, -3]
    rotation: [0, 0, 0, 1]
  