tags:
  - 
    id : 1
    translation: [0, 0, 0]
    rotation: [0, 0, 0, 1]
  - 
    id : 2
    translation: [-2.87, 0, 0]
    rotation: [0, 0, 0, 1]
  - 
    id : 3
    translation: [0, 0, -4.0]
    rotation: [0, 0, 0, 1]
  - 
    id : 4
    translation: [-2.87, 0, -4.0]
    rotation: [0, 0, 0, 1]
  - 
    id : 5
    translation: [0.0, 0, -8.0]
    rotation: [0, 0, 0, 1]
  - 
    id : 6
    translation: [-2.87, 0, -8.0]
    rotation: [0, 0, 0, 1]
  - 
    id : 8
    translation: [0, 0, -12.0]
    rotation: [0, 0, 0, 1]
    
  